## This notebook provides an example of how to use some functions related to genes.
### sum_pl : Calculate the proteomic load sum of any list of E. coli genes, in 1 of the 11 Carbon source conditions (Glucose, Fructose, etc)

In [1]:
from genes_functions import *

sum_pl takes two parameters: a list of genes and one of the 11 conditions corresponding to different carbon sources. The list of genes can be defined directly within the cell or loaded from a .csv file.

In [2]:
ls_gen = ["btuD", "dedA", "lpp"]

#name from the dataframe. 
df_genes = pd.DataFrame({ 'genes': ls_gen })
df_genes.to_csv('./genes_folder/df_genes.csv', index=False)
df_genes

  genes
0  btuD
1  dedA
2   lpp

In [3]:
genes = "df_genes.csv"
sum_pl(genes, 'Glucose')

Total proteome = 242.9413459379637 fg
in Glucose condition

3 genes were found in the list
2 with PL
Total proteomic load in the list is: 0.677349 fg
Corresponding to 0.28% of total proteome

In [4]:
ls_gen = ["oxyR", "tusA", "ydfB"]
ls_gen
#nombre que se le quiere dar al df. 
df_genes = pd.DataFrame({ 'genes': ls_gen })
os.makedirs('genes_folder', exist_ok=True)
df_genes.to_csv('./genes_folder/df_genes.csv', index=False)
df_genes

  genes
0  oxyR
1  tusA
2  ydfB

In [5]:
ls_gen = ['punC','punR']
df_genes = pd.DataFrame({ 'genes': ls_gen })
os.makedirs('genes_folder', exist_ok=True)
df_genes.to_csv('./genes_folder/df_genes.csv', index=False)

In [6]:
ls_genes = "df_genes.csv"
sum_pl(ls_genes, 'Glucose')

Total proteome = 242.9413459379637 fg
in Glucose condition

2 genes were found in the list
0 with PL
Total proteomic load in the list is: 0.000000 fg
Corresponding to 0.00% of total proteome

## search_synonyms: Find the synonymous genes in any list.

search_synonyms(genes). It takes only one parameter, which is the list of genes.

In [7]:
result = search_synonyms(ls_gen)
df_result = pd.DataFrame(result, columns=['Gen Reg12', 'Synonym'])
df_result

  Gen Reg12 Synonym
0      punR    punR
1      punC    punC

In [8]:
deg =['dfp', 'bcsB', 'rimN','uppS', 'yagP','ykgT']
result = search_synonyms(deg)
df_result = pd.DataFrame(result, columns=['Gen Reg12', 'Synonym'])
df_result

  Gen Reg12 Synonym
0       dfp     dfp
1      bcsB    bcsB
2      ispU    uppS
3      yagP    yagP
4      tsaC    rimN

In [9]:
#Find synonymous genes from a file.
my_list = "~/Notebooks/LIZ/Essential_genes/genes_keio276.csv"
file = pd.read_csv(my_list)
genes = file['genes'].tolist()
print(len(genes))

result = search_synonyms(genes)
df_result = pd.DataFrame(result, columns=['GenesReg12', 'Synonym'])
df_result.tail()

276

    GenesReg12 Synonym
271       obgE    obgE
272       lptC    lptC
273       lptA    lptA
274       tsaC    tsaC
275       lptF    lptF

In [10]:
my_list = "~/Notebooks/LIZ/Essential_genes/genes_pec302.csv"
file = pd.read_csv(my_list)
genes = file['genes'].tolist()
print(len(genes))

result = search_synonyms(genes)
df_result = pd.DataFrame(result, columns=['Genes_R12', 'Synonym'])
PEC_synomym = df_result.Genes_R12
print(len(PEC_synomym))
PEC_synomym.to_csv('~/Notebooks/LIZ/Ntbooks_finales/synonym/PEC_synonym.csv', index=False)

302
304

In [11]:
my_list = "~/Notebooks/LIZ/Essential_genes/genes_GL654_allessen.csv"
file = pd.read_csv(my_list)
genes = file['genes'].tolist()
print(len(genes))

result = search_synonyms(genes)
df_result = pd.DataFrame(result, columns=['Genes_R12', 'Synonym'])
PEC_synomym = df_result.Genes_R12
print(len(PEC_synomym))
PEC_synomym.to_csv('~/Notebooks/LIZ/Ntbooks_finales/synonym/GL_gen_synonym.csv', index=False)

654
627

In [12]:
my_list = "~/Notebooks/LIZ/Essential_genes/genes_GL_core521.csv"
file = pd.read_csv(my_list)
genes = file['genes'].tolist()
print(len(genes))

result = search_synonyms(genes)
df_result = pd.DataFrame(result, columns=['Genes_R12', 'Synonym'])
PEC_synomym = df_result.Genes_R12
print(len(PEC_synomym))
PEC_synomym.to_csv('~/Notebooks/LIZ/Ntbooks_finales/synonym/GL_core521_synonym.csv', index=False)

521
494

## find_TFs: Find TFs that regulate all genes in any given list.

In [13]:
find_TFs(my_list)

521 genes were found in the list
696 interactions created
113 TFs regulate the total network
17 are TFs no essential

['MazE', 'RacR', 'YefM', 'RplD', 'RplM', 'RpmE', 'RpsO', 'CsrA', 'MqsA', 'DicA', 'BirA', 'RplT', 'AlaS', 'RplY', 'LexA', 'RpsA', 'RpsH']

In [14]:
genes_rsb =['rbsD', 'rbsA', 'rbsC','rbsB', 'rbsK','rbsR', 'yieO', 'cspC', 'hprR', 'narL']
result = search_synonyms(genes_rsb)
df_result = pd.DataFrame(result, columns=['Gen Reg12', 'Synonym'])
df_result

  Gen Reg12 Synonym
0      narL    narL
1      rbsA    rbsA
2      rbsB    rbsB
3      rbsC    rbsC
4      rbsD    rbsD
5      rbsK    rbsK
6      rbsR    rbsR
7      hsrA    yieO
8      cspC    cspC
9      hprR    hprR

In [15]:
df_genes = pd.DataFrame({ 'genes': genes_rsb })
os.makedirs('genes_folder', exist_ok=True)
df_genes.to_csv('./genes_folder/df_genes.csv', index=False)
df_genes

  genes
0  rbsD
1  rbsA
2  rbsC
3  rbsB
4  rbsK
5  rbsR
6  yieO
7  cspC
8  hprR
9  narL

In [16]:
genes = "df_genes.csv"
sum_pl(genes, 'Glucose')

Total proteome = 242.9413459379637 fg
in Glucose condition

10 genes were found in the list
8 with PL
Total proteomic load in the list is: 1.038808 fg
Corresponding to 0.43% of total proteome

In [17]:
genes_rsb =['galK', 'galT', 'galE', 'galM', 'galR']
result = search_synonyms(genes_rsb)
df_result = pd.DataFrame(result, columns=['Gen Reg12', 'Synonym'])
df_result

  Gen Reg12 Synonym
0      galE    galE
1      galK    galK
2      galR    galR
3      galT    galT
4      galM    galM

In [18]:
df_genes = pd.DataFrame({ 'genes': genes_rsb })
os.makedirs('genes_folder', exist_ok=True)
df_genes.to_csv('./genes_folder/df_genes.csv', index=False)
lista_genes = "df_genes.csv"
sum_pl(lista_genes, 'Glucose')

Total proteome = 242.9413459379637 fg
in Glucose condition

5 genes were found in the list
5 with PL
Total proteomic load in the list is: 0.156178 fg
Corresponding to 0.06% of total proteome

In [19]:
df_genes = pd.DataFrame({ 'genes': genes_rsb })
os.makedirs('genes_folder', exist_ok=True)
df_genes.to_csv('./genes_folder/df_genes.csv', index=False)
path = "./genes_folder/df_genes.csv"
find_TFs(path)
shutil.rmtree('genes_folder')

5 genes were found in the list
24 interactions created
7 TFs regulate the total network
1 are TFs no essential

['GalR']

In [20]:
genes_rsb =['uppS', 'ydiL', 'mlaB', 'ydfB', 'tdcF', 'yejM','mtlR']
result = search_synonyms(genes_rsb)
df_result = pd.DataFrame(result, columns=['Gen Reg12', 'Synonym'])
df_result

  Gen Reg12 Synonym
0      ydfB    ydfB
1      mtlR    mtlR
2      lapC    yejM
3      ispU    uppS
4      ydiL    ydiL
5      tdcF    tdcF
6      mlaB    mlaB

### gene_category: Function to locate the categorization of a specific gene based on individual fitness data.

In [21]:
# Search for the gene 'galE' only under the condition 'Glucose'.
galE_Ace = gene_category('galE', 'Glucose')
galE_Ace

galE categorized in Glucose is a gene

      category
278  No effect

In [22]:
galE_Glu = gene_category('glnA', 'Glucose')  #manX
galE_Glu

glnA categorized in Glucose is a gene

      category
296  Essential

In [23]:
#search for multiple genes.
genes = ['galE', 'rbsR', 'rpoH']
for gen in genes:
    results = gene_category(gen)
    if results is not None:
        if len(results) == 0:
            print('\n')
        else:
            print(results, '\n')

galE categorized in all conditions
         condition   category
278        Glucose  No effect
4066            LB  No effect
7854   Glucosamine  No effect
11642     Glycerol  No effect
15430       Xylose  No effect
19218      Mannose  No effect
23006    Galactose  Important
26794     Fructose  Essential
30582      Acetate  Essential
34370     Pyruvate  No effect
38158    Succinate  No effect

rbsR categorized in all conditions
         condition   category
649        Glucose  Enhancing
4437            LB  No effect
8225   Glucosamine  No effect
12013     Glycerol  Enhancing
15801       Xylose  Enhancing
19589      Mannose  Enhancing
23377    Galactose  Enhancing
27165     Fructose  Enhancing
30953      Acetate  No effect
34741     Pyruvate  Enhancing
38529    Succinate  Enhancing

rpoH is not in the fitness base

In [24]:
#search for multiple genes.
genes = ['metJ', 'hipB', 'rpoN','hns','ygeH', 'yddM', 'hipH', 'dicD', 'cspI']
for gen in genes:
    results = gene_category(gen)
    if results is not None:
        if len(results) == 0:
            print('\n')
        else:
            print(results, '\n')

metJ is not in the fitness base


hipB is not in the fitness base


rpoN is not in the fitness base


hns is not in the fitness base


ygeH is not in the fitness base


yddM is not in the fitness base


hipH is not in the fitness base


dicD is not in the fitness base


cspI is not in the fitness base

In [25]:
cstA = gene_category('pgi')
cstA

pgi categorized in all conditions

         condition   category
551        Glucose  Important
4339            LB  Important
8127   Glucosamine  No effect
11915     Glycerol  Important
15703       Xylose  Important
19491      Mannose  No effect
23279    Galactose  No effect
27067     Fructose  Important
30855      Acetate  Important
34643     Pyruvate  No effect
38431    Succinate  No effect

In [26]:
#Searches for synonyms and then the TFs that regulate that list.
my_list = "~/Notebooks/LIZ/VISEAGO/df_esse368.csv"
file = pd.read_csv(my_list)
genes = file['genes'].tolist()
print(len(genes))

result = search_synonyms(genes)
df_result = pd.DataFrame(result, columns=['Genes_R12', 'Synonym'])
PEC_synomym = df_result.Genes_R12
print(len(PEC_synomym))
PEC_synomym.to_csv('~/Notebooks/LIZ/VISEAGO/df_esse368_synon.csv', index=False)

368
368

In [27]:
find_TFs(my_list)

368 genes were found in the list
591 interactions created
95 TFs regulate the total network
12 are TFs no essential

['RplD', 'RplM', 'RpmE', 'RpsO', 'CsrA', 'DicA', 'RplT', 'AlaS', 'RplY', 'LexA', 'RpsA', 'RpsH']

In [28]:
my_list = "~/Notebooks/LIZ/VISEAGO/df_genes_fitness_enhancing.csv"
file = pd.read_csv(my_list)
genes = file['genes'].tolist()

result = search_synonyms(genes)
df_result = pd.DataFrame(result, columns=['Genes_R12', 'Synonym'])
PEC_synomym = df_result.Genes_R12
print(len(PEC_synomym))
PEC_synomym.to_csv('~/Notebooks/LIZ/VISEAGO/df_genes_fitness_enhancing_synon.csv', index=False)
find_TFs(my_list)

19
18 genes were found in the list
65 interactions created
35 TFs regulate the total network
5 are TFs no essential

['RbsR', 'YebK', 'Hfq', 'GcvA', 'IscR']

In [29]:
#search for multiple genes.
genes = [ 'folK','degS','mlaB','rpoN', 'rprA', 'rpsA', 'rpsB',
         'rpsD', 'rpsG', 'rpsH', 'rpsO', 'cra'] 

for gen in genes:
    results = gene_category(gen)
    if results is not None:
        if len(results) == 0:
            print('\n')
        else:
            print(results, '\n')

folK categorized in all conditions
         condition   category
1048       Glucose  Essential
4836            LB  Essential
8624   Glucosamine  Essential
12412     Glycerol  Essential
16200       Xylose  Essential
19988      Mannose  Essential
23776    Galactose  Essential
27564     Fructose  Essential
31352      Acetate  Essential
35140     Pyruvate  Essential
38928    Succinate  Essential

degS is not in the fitness base


mlaB categorized in all conditions
         condition   category
3554       Glucose  No effect
7342            LB  No effect
11130  Glucosamine  No effect
14918     Glycerol  No effect
18706       Xylose  No effect
22494      Mannose  No effect
26282    Galactose  No effect
30070     Fructose  No effect
33858      Acetate  No effect
37646     Pyruvate  No effect
41434    Succinate  No effect

rpoN is not in the fitness base


rprA categorized in all conditions
         condition   category
2191       Glucose  No effect
5979            LB  No effect
9767   Glucosamine  No effect
13555     Glycerol  No effect
17343       Xylose  No effect
21131      Mannose  No effect
24919    Galactose  No effect
28707     Fructose  No effect
32495      Acetate  No effect
36283     Pyruvate  No effect
40071    Succinate  No effect

rpsA is not in the fitness base


rpsB is not in the fitness base


rpsD is not in the fitness base


rpsG categorized in all conditions
         condition   category
693        Glucose  No effect
4481            LB  Important
8269   Glucosamine  No effect
12057     Glycerol  Enhancing
15845       Xylose  Enhancing
19633      Mannose  Enhancing
23421    Galactose  Enhancing
27209     Fructose  Enhancing
30997      Acetate  No effect
34785     Pyruvate  Enhancing
38573    Succinate  Enhancing

rpsH is not in the fitness base


rpsO is not in the fitness base


cra categorized in all conditions
         condition   category
262        Glucose  Important
4050            LB  Important
7838   Glucosamine  No effect
11626     Glycerol  Important
15414       Xylose  Essential
19202      Mannose  Essential
22990    Galactose  Essential
26778     Fructose  Important
30566      Acetate  Important
34354     Pyruvate  Essential
38142    Succinate  Essential

In [32]:
ls_gen = ["sspA", "dnaK", "yafN", "rmf",  "arfB", "slyA", "cspC", "rlmA", "srmB", "selU",
"rpoS", "gcvA", "gcvH", "rcsB", "pnp",  "greA", "fis",  "dusB", "iraP", "rpsG",
"arcB", "rsmG", "rbsR", "hupA", "rapA", "hfq",  "rpsR", "ydcI", "rsmC", "rimI", "ettA", "proQ"]
df_genes = pd.DataFrame({ 'genes': ls_gen })
os.makedirs('genes_folder', exist_ok=True)
df_genes.to_csv('./genes_folder/df_genes.csv', index=False)

In [33]:
ls_genes = "df_genes.csv"
sum_pl(ls_genes, 'Glucose')

Total proteome = 242.9413459379637 fg
in Glucose condition

32 genes were found in the list
30 with PL
Total proteomic load in the list is: 8.559608 fg
Corresponding to 3.52% of total proteome